# Generated by Django 4.2.2 on 2023-06-30 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
        migrations.AlterField(
            model_name='testincluded',
            name='array_included',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
        migrations.AlterField(
            model_name='testincludedrelation',
            name='array_included_relation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=2),
        ),
    ]
