# Generated by Django 4.2.2 on 2023-09-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0003_alter_test_bool_alter_test_choice_int_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testincluded',
            name='foreign_key_included',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_included', to='adrf_jsonapi.testincludedrelation'),
        ),
    ]
