# Generated by Django 4.2.2 on 2023-09-21 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0004_alter_testincluded_foreign_key_included'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_included', to='adrf_jsonapi.testincluded'),
        ),
        migrations.AlterField(
            model_name='testincluded',
            name='foreign_key_included',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_included_relation', to='adrf_jsonapi.testincludedrelation'),
        ),
    ]
