# Generated by Django 4.2.2 on 2023-09-21 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0005_alter_test_foreign_key_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testincluded',
            table='test_included',
        ),
        migrations.AlterModelTable(
            name='testincludedrelation',
            table='test_included_relation',
        ),
    ]
