# Generated by Django 4.2.2 on 2023-09-21 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0006_alter_testincluded_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'default_related_name': 'test', 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testincluded',
            options={'default_related_name': 'test_included', 'verbose_name': 'Test Included', 'verbose_name_plural': 'Test Included'},
        ),
        migrations.AlterModelOptions(
            name='testincludedrelation',
            options={'default_related_name': 'test_included_relation', 'verbose_name': 'Test Included Relation', 'verbose_name_plural': 'Test Included Relations'},
        ),
    ]
