# Generated by Django 4.2.2 on 2023-09-25 19:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0008_alter_testincludedrelation_array_included_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testincludedrelation',
            name='array_included_relation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, null=True, size=2),
        ),
    ]
