# Generated by Django 4.2.2 on 2023-09-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adrf_jsonapi', '0009_alter_testincludedrelation_array_included_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDirectCon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=128)),
                ('int', models.IntegerField(default=1)),
                ('bool', models.BooleanField(default=False)),
                ('choice_int', models.IntegerField(choices=[(1, 'One'), (2, 'Two')], default=1)),
                ('choice_str', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], default='UK', max_length=9)),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'default_related_name': 'test',
            },
        ),
    ]
